### ISSUE TITLE
Possible performance improvement

### ISSUE THREAD

**Issue by mm3141** [totalschaden/copilot#18]
Hi, 
copilot spends a lot of time with manually parsing the entity list:

![image](https://user-images.githubusercontent.com/7443263/117352838-bdb1fb80-aeaf-11eb-9126-1106db992a39.png)

Is there a reason why the pre-processed entity collections are not used, for example `GameController.EntityListWrapper.ValidEntitiesByType[EntityType.Monster]`?

**Comment by totalschaden** [comment]
Not sure I understand it, its already using GameController.EntityListWrapper.ValidEntitiesByType[EntityType.Monster].Where(x => x != null ....

I was playing around with it due to the TC Fork entity error spam, or do you mean use it in the enemy checks only instead of using
enemys = GameController.EntityListWrapper.ValidEntitiesByType[EntityType.Monster].Where(x => x != null .... ?

wont it cause alot more load due to filtering then, it would run multiple times when multiple skills are active.

If you on the TC Discord send me a message

**Comment by mm3141** [comment]
Nice, you seem to have fixed it already. Took that measurement a few days ago, but only now found some time to look into that.
